(torchx/resources) Improve error message when named resource is not found (#641)
Summary:
Improves error message when the no registered named resource is found by:

1. Suggesting one by closest match from the registered named resource
2. If no close match is found then listing all the available registered named resources

Here's an example:

```
(venv39) ubuntu@ip-10-2-87-95(main|✚1)% torchx run -s aws_batch dist.ddp -j 1x8 -h p4dn.24xlarge --script mfive/examples/data/datakit_datapipe.py
torchx 2022-10-31 23:47:04 INFO     loaded configs from /home/ubuntu/workspace/mfive/.torchxconfig
Traceback (most recent call last):
<.... OMITTED FOR BREVIT...>
  File "/home/ubuntu/workspace/torchx/torchx/specs/__init__.py", line 81, in __getitem__
    raise KeyError(f"`{key}` not registered as a named resource. {msg}")
KeyError: 'No named resource found for `p4dn.24xlarge`. Did you mean `aws_p4d.24xlarge`?'
```

Also registers p4d and p4de types (I forgot to register them in my other PR).

Pull Request resolved: https://github.com/pytorch/torchx/pull/641

Reviewed By: kurman

Differential Revision: D40903913

Pulled By: d4l3k

fbshipit-source-id: f0af2baa325cd9e652da2b33f446c2343ba07e1a