Update black (#485)
Summary:
If you try and run `scripts/lint.sh` it'll fail with

```
if [ ! "$(black --version)" ]
then
    echo "Please install black."
    exit 1
```

which is failing because it used to use a now deprecated hidden function

```
(ray) ubuntu@ip-172-31-16-198:~/torchx$ black .
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ray/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/black/__init__.py", line 1322, in patched_main
    patch_click()
  File "/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/black/__init__.py", line 1308, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/__init__.py)
```

Tons of people have this issue here https://github.com/pallets/click/issues/2225

Pull Request resolved: https://github.com/pytorch/torchx/pull/485

Test Plan:
1. `pip install black==22.3.0`
2. `./scripts/lint.sh` succeeds

Reviewed By: d4l3k

Differential Revision: D36385103

Pulled By: msaroufim

fbshipit-source-id: 6478cb2859b8f32f389806ec556bbed9c697880d