github/workflows: switch to configure-aws-credentials (#386)
Summary:
Our integration tests are hitting an error when acquiring AWS credentials.
```
botocore.errorfactory.InvalidIdentityTokenException: An error occurred (InvalidIdentityToken) when calling the AssumeRoleWithWebIdentity operation: Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements
```

https://github.com/pytorch/torchx/runs/5147711223?check_suite_focus=true

This switches to the `aws-actions/configure-aws-credentials` GitHub action since it includes retries as of https://github.com/aws-actions/configure-aws-credentials/pull/350

Pull Request resolved: https://github.com/pytorch/torchx/pull/386

Test Plan: CI

Reviewed By: kiukchung

Differential Revision: D34158910

Pulled By: d4l3k

fbshipit-source-id: 6b6b9516b0233ea5b0f05f0fc5e6483829587c82