(torchx/docs) replace links to github.com/pytorch/torchx with github.com/meta-pytorch/torchx (#1131)
Summary:

TorchX migrated from https://github.com/pytorch/torchx to https://github.com/meta-pytorch/torchx hence need to replace all links in docstrings/rst to point to the new repo location.

Fixes errors such as:
```
Warning, treated as error:
/home/runner/work/torchx/torchx/docs/source/schedulers/kubernetes.rst:8:broken link: https://github.com/pytorch/torchx/issues/120 (404 Client Error: Not Found for url: https://github.com/pytorch/torchx/issues/120)
make: *** [Makefile:29: linkcheck] Error 2
(schedulers/kubernetes: line    8) 
Error: Process completed with exit code 2.
```

Reviewed By: AbishekS

Differential Revision: D83262154