add 'tabulate' to the requirements.txt since the CLI cmd_list uses it (#627)
Summary:
Fixes a bug introduced in https://github.com/pytorch/torchx/pull/579/files#diff-0aff65b8fe78257a723972926d63b801c495e54669248db41bed7536055aad92

Using `tabulate` in `cmd_list.py` but not adding it to `requirements.txt` causes torchx CLI to fail:

```
$ torchx runopts aws_batch

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/venv39/bin/torchx", line 5, in <module>
    from torchx.cli.main import main
  File "/home/ubuntu/.pyenv/versions/3.9.13/envs/venv39/lib/python3.9/site-packages/torchx/cli/main.py", line 17, in <module>
    from torchx.cli.cmd_list import CmdList
  File "/home/ubuntu/.pyenv/versions/3.9.13/envs/venv39/lib/python3.9/site-packages/torchx/cli/cmd_list.py", line 11, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

Pull Request resolved: https://github.com/pytorch/torchx/pull/627

Reviewed By: priyaramani

Differential Revision: D40742523

Pulled By: d4l3k

fbshipit-source-id: 092bfce9ee6857806a84b9d6b5f0250151413b72